[project]
name = "tescalera"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "drawsvg>=2.4.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.3",
    "numpy>=2.2.5",
    "shapely>=2.1.0",
    "svgwrite>=1.4.3",
]
